schema_version: 1

context:
  name: requests
  version: "2.32.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/requests-${{ version }}.tar.gz
  sha256: dbba0bac56e100853db0ea71b82b4dfd5fe2bf6d3754a8893c3af500cec7d7cf

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - certifi >=2017.4.17
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - urllib3 >=1.21.1,<3
  run_constraints:
    # https://github.com/psf/requests/blob/da9996fe4dc63356e9467d0a5e10df3d89a8528e/requests/__init__.py#L103-L115
    - chardet >=3.0.2,<6

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - requests
      pip_check: true

about:
  homepage: http://python-requests.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Requests is an elegant and simple HTTP library for Python, built with ♥.
  repository: https://github.com/psf/requests

extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - pelson
    - sigmavirus24
    - ocefpaf
    - carlodri
