travis:
  secure:
    BINSTAR_TOKEN: BzCrNu0QqEMWXl6EfUsJSg7I6k8D5s8AJ74Kg3hBaOc4vT4oJxGVy8tZ9Rz9e90YWmsSegT4ZYRi6IfIl+hyZb07jCmcIBmbOQeBr8Y5d1gGIpVY8EVkCiGQ6hDyHOjuC12y5rzPhWcmX5GgE1l9iwb43A/WMdNVg8MyVUsHmYb8JQqpLs6vV+kZlm0nZuHwgBD7LucrqNF/mLgT/jbS0tpWetq4wFEtx4y7KiNYL5orC2poWhkkjgZsnq5FGdUACtze5TGyErDgNUVT8qYD30DHRtciDCT4QRkhdDPCOrThV7giHmlXcoE8VyDfTuCyAo+quXMzRN5vhPvZb5j/+7RR7hNtAVOr7CPfpIx7zsWVlx7fG/XNlGuoy4l3zAfa43tPHdCsscFQ/VqmGxPqimOnmXuJP1COOVTFfjPiE45e38iTp1PDUvumW54erZ0eBgWbFo8FrI7paxWDDkZ1QG0OqqfMMzWCbOTa0HqOD1IEp+EoCfySWZ+4I8m/fwdLxCNWdM635IG69z4y+WanGA432z59Lpay6vGW1/jpqEeHzt9pA88D3jB0Srmy0tmBpTq82MP0tmW/gv1FBXzz8ghwz7bVQJFojE8OFuWEjEjdKleVo6JdtA01R/zGfaw6dymR6jz61byHUli+oexzrT7/qRq/K89OwWK640BW1Ws=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
