conda_build_tool: rattler-build
conda_install_tool: pixi

bot:
  inspection: update-grayskull
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
